/*
 * Team Name: Andrew's Honor Squad 2: High Honors
 * Team Members: Justin Jiang, Samir Leal, Phi Nguyen, Eric Sullivan
 * Date: 04-30-15
 *
 * Purpose: You and your team members will simulate to develop the software called
 * "Medical Doctor".  The software will be used in hospital for managing and updating
 * not only the patient information but also prescription, and other physical test.
 * The software should be developed with well-designed Graphical User Interface (GUI)
 * so that medical doctors can easily access and manage the patient information.
 *
 * Program Contents: The "Medical Doctor" software should have following contents on GUI:
 * 1. Registration
 * 2. Doctor General Practice
 * 3. Nursing
 */
package Gui;

import Backend.*;
import java.awt.event.*;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author jusji_000
 */
public class RegistrationSearch extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationSearch
     * initialize the JFrame and fills the table.
     */
    public RegistrationSearch() {
        initComponents();
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jButton2.addActionListener(new Handler());
        jButton1.addActionListener(new Handler());
        jButton4.addActionListener(new Handler());
        jButton3.addActionListener(new Handler());
        jMenuItem1.addActionListener(new Handler());
        jMenuItem2.addActionListener(new Handler());
        buildTable();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registration");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SSN", "Name","First Name","Last Name","DOB" }));

        jButton1.setText("Search Patient");

        jTable1.setModel(new NonEditableTable());
        String[] columns = {"SSN","First Name","Last Name","Address","Medical Insurance", "DOB","ZIP", "Gender","Next Visit"};
        ((NonEditableTable) jTable1.getModel()).setColumnIdentifiers(columns);
        jTable1.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("New Patient");

        jButton3.setText("Edit Patient");

        jButton4.setText("Delete Patient");

        jMenu1.setText("File");

        jMenuItem1.setText("Logout");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4))
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(jLabel2)
                .addContainerGap(337, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 // <editor-fold defaultstate="collapsed" desc="ActionListener NEEDS COMMENTS"> 
    
    /**
     * ActionListener for the new patient, edit patient, delete patient buttons,Search button, and JMenuItems.
     * the new patient button opens a new registration window and closes this window
     * the edit patient button open a registration window with all the field filled with the selected patients info
     * the delete patient button deletes the selected patient from the database and update the JTable.
     * search buttons refills the JTable with a specified search parameter 
     * JMenuItems alway the user to logout or exit
     */
    public class Handler implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            //Logout JMenuItem
            if (e.getSource() == jMenuItem1) {
                new Login().setVisible(true);
                dispose();
            }
            //Exit JMenuItem
            if (e.getSource() == jMenuItem2) {
                System.exit(0);
            }
            //Delete Patient button
            if (e.getSource() == jButton4) {
                try {
                    
                    //asks if the user really wants to delete
                    int yesno = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?", "Delete", JOptionPane.YES_NO_CANCEL_OPTION);
                    if (yesno == JOptionPane.YES_OPTION) {
                        Class.forName("com.mysql.jdbc.Driver");// Creates a connection to the database
                        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/honorsmedicaldoctor", "HonorsAdmin", "h0n3r5a2m1n");
                        Statement stmt = con.createStatement();
                        String sql = "DELETE FROM Patients WHERE SSN = '" + jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0) + "'";
                        stmt.executeUpdate(sql);
                        buildTable();
                        con.close();
                        stmt.close();
                    }
                } catch (ClassNotFoundException ex) {
                    ex.printStackTrace();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                } catch (Exception ex){
                    
                }
            }
            //new patient button
            if (e.getSource() == jButton2) {
                new Registration().setVisible(true);
                dispose();
            }
            //edit patient button
            if (e.getSource() == jButton3) {
                if (jTable1.getSelectedRow() != -1) {
                    try {
                        //pulls the information from the JTable and makes a filled registration window    
                        new Registration((String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0), (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1),
                                (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2),
                                (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3),
                                (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4),
                                (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 5),
                                (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 6),
                                (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 7),
                                (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 8)).setVisible(true);
                        dispose();
                    } catch (Exception ex) {
                         ex.printStackTrace();
                    }
                }
            }
            //search button
            if (e.getSource() == jButton1) {
                buildTable();
            }
        }
    }

    public void buildTable() {
        int rows = jTable1.getRowCount();
        for (int i = 0; i < rows; i++) {
            ((javax.swing.table.DefaultTableModel) jTable1.getModel()).removeRow(0);
        }

        // Gets the username from the text field
        String query = jTextField1.getText();

        // Strings for the password and section from the database
        String firstN = "";
        String lastN = "";
        String add = "";
        String medInsur = "";
        String dob = "";
        String zip = "";
        String gender = "";
        String nextV = "";

        try {

            // Creates a connection to the database
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/honorsmedicaldoctor", "HonorsAdmin", "h0n3r5a2m1n");
            Statement stmt = con.createStatement();
            String sql = "";
            // SQL statement that returns all of the usernames that match the username entered in the text field
            switch (jComboBox1.getSelectedIndex()) {
                case 0:
                    sql = "SELECT * FROM Patients WHERE SSN LIKE '" + query + "%'";
                    break;
                case 1:
                    String[] temp = query.split(" ");
                    sql = "SELECT * FROM Patients WHERE (FirstName LIKE '" + temp[0] + "%' AND LastName LIKE '" + temp[1] + "%')";
                    break;
                case 2:
                    sql = "SELECT * FROM Patients WHERE FirstName LIKE '" + query + "%'";
                    break;
                case 3:
                    sql = "SELECT * FROM Patients WHERE LastName LIKE '" + query + "%'";
                    break;
                default:
                    sql = "SELECT * FROM Patients WHERE DOB LIKE '%" + query + "%'";
                    break;
            }

            ResultSet rs = stmt.executeQuery(sql);

            // Loop through all the results and add each to the table model
            while (rs.next()) {

                // Data from the database for that result
                query = rs.getString("SSN");
                firstN = rs.getString("FirstName");
                lastN = rs.getString("LastName");
                add = rs.getString("Address");
                medInsur = rs.getString("MedicalInsurance");
                dob = rs.getString("DOB");
                zip = rs.getString("zip");
                gender = rs.getString("gender");
                nextV = rs.getString("NextVisit");

                // Adds the data to the table model
                ((javax.swing.table.DefaultTableModel) jTable1.getModel()).addRow(new Object[]{query, firstN, lastN, add, medInsur, dob, zip, gender, nextV});

            }

            // Closes the connection to the database
            rs.close();
            stmt.close();
            con.close();

        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    // </editor-fold>  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    }
